### Drug Overview

```{r}
selectInput(
  inputId = "selected_drugs",
  label = "Select one or more drugs:",
  choices = sort(unique(faers_simulated$Drug)),
  selected = sort(unique(faers_simulated$Drug))[1],
  multiple = TRUE
)

filtered_data_drug <- reactive({
  req(input$selected_drugs)

  filtered_data() |>  # aplica filtros gerais
    filter(Drug %in% input$selected_drugs)
})


```

Value boxes {data-width=650}
-----------------------------------------------------------------------

### Total Reports

```{r}
renderValueBox({
  valueBox(
    value = nrow(filtered_data_drug()),
    caption = "Total Reports",
    icon = "fas fa-notes-medical",
    color = "primary"
  )
})
```

### Serious Reports
```{r}
renderValueBox({
  serious_count <- filtered_data_drug() |>
    filter(Seriousness == "Serious") |>
    nrow()

  valueBox(
    value = serious_count,
    caption = "Serious Reports (Excluding death)",
    icon = "fas fa-exclamation-triangle",
    color = "warning"
  )
})
```

### Death Reports
```{r}
renderValueBox({
  death_count <- filtered_data_drug() |>
    filter(Seriousness == "Death") |>
    nrow()

  valueBox(
    value = death_count,
    caption = "Death report",
    icon = "fas fa-skull-crossbones",
    color = "danger"
  )
})

```

Graphics
-----------------------------------------------------------------------
### Graphics {data-width=50}
```{r}
renderPlotly({
  stack_var <- input$summary_view  # Ex: "Gender", "Age_group", etc.

  plot_data <- filtered_data_drug() |>
    group_by(Year, across(all_of(stack_var))) |>
    summarise(Count = n(), .groups = "drop")

  plot_ly(
    data = plot_data,
    x = ~Year,
    y = ~Count,
    color = ~get(stack_var),
    type = "bar"
  ) |>
    layout(
      barmode = "stack",
      xaxis = list(title = "Year"),
      yaxis = list(title = "Number of Reports"),
      legend = list(title = list(text = stack_var))
    )
})
```

### Report receiveds {data-width=50}

```{r}
renderReactable({
  pivot_var <- input$summary_view

  table_data <- filtered_data_drug() |>
    group_by(Year, across(all_of(pivot_var))) |>
    summarise(Count = n(), .groups = "drop") |>
    tidyr::pivot_wider(
      names_from = all_of(pivot_var),
      values_from = Count,
      values_fill = 0
    ) |>
    arrange(Year)

  reactable(
    table_data,
    bordered = TRUE,
    highlight = TRUE,
    striped = TRUE,
    defaultColDef = colDef(align = "center"),
    pagination = FALSE
  )
})


```
