# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(bsicons)
library(bslib)
library(data.table)
library(dplyr)
library(highcharter)
library(htmlwidgets)
library(reactable)
library(rhino)
library(shinyWidgets)
